services:
  - type: web
    name: medbot-backend
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install wheel
      PIP_NO_CACHE_DIR=1 pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: PIP_NO_CACHE_DIR
        value: 1
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHONPATH
        value: .
    autoDeploy: true
    healthCheckPath: /health
    scaling:
      minInstances: 1
      maxInstances: 1