services:
  - type: web
    name: medbot-backend
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: PYTHONPATH
        value: .
    autoDeploy: true
    healthCheckPath: /docs
    scaling:
      minInstances: 1
      maxInstances: 1